# generated by datamodel-codegen:
#   filename:  commons.schema.json
#   timestamp: 2025-03-03T18:46:06+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import Field, RootModel


class Commons(RootModel[Any]):
    root: Any = Field(..., description='Commons objects', title='Commons')


class DefaultArray(RootModel[List]):
    root: List = Field(..., max_length=100, min_length=1)
