# generated by datamodel-codegen:
#   filename:  products_unified.schema.json
#   timestamp: 2025-03-03T18:46:06+00:00

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel


class Products(RootModel[List[str]]):
    root: List[str] = Field(
        ...,
        description='The products in the catalog',
        max_length=10,
        min_length=1,
        title='Products',
    )
